name: '测试player'
type: 'common'
pages:
  - name: 'TestPage'
    conditions:
      - {pattern: 'XQueryPointer', x_range: [0, 0.1], y_range: [0, 0.1]}
modes:
  - name: '测试mode'
    page_operations:
      - page: 'TestPage'
        operations:
          - {type: 'click', pattern: 'Test'}
    other_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
    undefined_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
