name: 'txbm'
type: 'common'
pages:
  - name: 'skip'
    conditions:
      - {pattern: 'SKIP'}
  - name: 'clear'
    conditions:
      - {pattern: '再次挑战', x_range: [0.1, 0.3]}
      - {pattern: '返回地图', x_range: [0.4, 0.6]}
      - {pattern: '前往下关', x_range: [0.7, 0.9]}
  - name: 'clear2'
    conditions:
      - {pattern: '再次挑战', x_range: [0.2, 0.5]}
      - {pattern: '返回地图', x_range: [0.5, 0.7]}
  - name: '开始'
    conditions:
      - {pattern: '开始'}
      - {pattern: '军团扫荡'}
  - name: '确认'
    conditions:
      - {pattern: '确认', x_range: [0.4, 0.6], y_range: [0.3, 0.4]}
      - {pattern: '确定', x_range: [0.65, 0.75], y_range: [0.55, 0.65]}
      - {pattern: '取消', x_range: [0.25, 0.35], y_range: [0.55, 0.65]}
  - name: '获得奖励'
    conditions:
      - {pattern: '获得奖励', x_range: [0.4, 0.6], y_range: [0.35, 0.45]}
      - {pattern: '确定', x_range: [0.4, 0.6], y_range: [0.5, 0.6]}
  - name: '等级提升'
    conditions:
      - {pattern: '等级提升', x_range: [0.2, 0.3], y_range: [0.5, 0.6]}
modes:
  - name: '刷关'
    page_operations:
      - page: 'skip'
        operations:
          - {type: 'click', pattern: 'SKIP'}
      - page: 'clear'
        operations:
          - {type: 'click', pattern: '前往下关'}
      - page: '开始'
        operations:
          - {type: 'click', pattern: '开始'}
      - page: '确认'
        operations:
          - {type: 'click', pattern: '确定'}
      - page: '获得奖励'
        operations:
          - {type: 'click', pattern: '确定'}
      - page: '等级提升'
        operations:
          - {type: 'click', point: [0.5, 0.8]}
    other_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
    undefined_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
  - name: '单刷'
    page_operations:
      - page: 'skip'
        operations:
          - {type: 'click', pattern: 'SKIP'}
      - page: 'clear'
        operations:
          - {type: 'click', pattern: '再次挑战'}
      - page: 'clear2'
        operations:
          - {type: 'click', pattern: '再次挑战'}
      - page: '开始'
        operations:
          - {type: 'click', pattern: '开始'}
      - page: '确认'
        operations:
          - {type: 'click', pattern: '确定'}
      - page: '获得奖励'
        operations:
          - {type: 'click', pattern: '确定'}
      - page: '等级提升'
        operations:
          - {type: 'click', point: [0.5, 0.8]}
    other_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
    undefined_page_operations:
      operations:
        - {type: 'sleep', time: 1000}
