
ocr:
  type: 'paddleocr'
  host: '192.168.31.40'
  port: 8868
  recv_timeout: 10

player:
  configs: [player/blhx.yaml, player/txbm.yaml, player/test.yaml]
  name: txbm
  mode: 刷关

capture:
  window_class: scrcpy

operation:
  window_class: scrcpy

