
ocr:
  type: 'paddleocr'
  host: '192.168.31.40'
  port: 8868
  recv_timeout: 10

player:
  configs: [player/blhx.yaml]
  # config: player/test.yaml
  name: blhx
  mode: 3-4

capture:
  window_class: scrcpy

operation:
  window_class: scrcpy

